### ISSUE TITLE
Is there a repo for the web version ?

### ISSUE THREAD

**Issue by moeenio** [STiBaRC/stibarc_app#3]
I would like to contirbute to the css, to try to make it look better.

**Comment by mkacct** [comment]
This repo has the CSS, you can do so here I think

**Comment by herronjo** [comment]
No, but the app is based on the web version, so if you make a change here, I’ll just backport it to the site. I’ll probably open a site repo soon.

**Comment by moeenio** [comment]
Ok thanks!

**Comment by herronjo** [comment]
https://github.com/STiBaRC/stibarc_web

**Comment by moeenio** [comment]
OK
